### ISSUE TITLE
href template

### ISSUE THREAD

**Issue by agborkowski** [wmdmark/backbone-rivets-example#4]
```
<li rv-each-contact="root:contacts" rv-id="contact.cid">
...
    <h3>Tags</h3>
    <a rv-href="contact.cid" href="#/tags/edit/{contact.cid}">add tag</a>
```

how can i push args to link with backbone-rivets ?

**Comment by wmdmark** [comment]
Unfortunately I don't think there's a good way to pass arguments to rivets binders at the moment. Does your code work if you leave off the "rv-href" attribute?

**Comment by agborkowski** [comment]
no ;), but i use ur workaround for this problem:

view

```
<a rv-href="contact.getTagsEditLink < :cid">add tag</a>
```

model

```
 getTagsEditLink: function () {
        return '#/tags/edit/' + this.cid;
    }
```

why u think its not a good idea to pass template inside args ? anyway now 

```
<a rv-href="contact.getTagsEditLink < :cid">add tag to <span rv-text="contact.name"></span></a>
```

instead of just use {}...
