### ISSUE TITLE
Deep models

### ISSUE THREAD

**Issue by azproduction** [wmdmark/backbone-rivets-example#5]
Hi, 

Great demo and article for those who want to start working with rivets and backbone!

I think that it is worth mentioning dealing with deep backbone structures (nested models). For some apps it is a bad practice, but in some cases when you have document-based DBs you have to use those. 

For dealing with that I have a nice [adapter](https://github.com/azproduction/rivets-backbone-adapter) along with [demo](http://azproduction.ru/rivets-backbone-adapter/example/index.html).

I hope it help your readers ;)

**Comment by wmdmark** [comment]
Hi @azproduction, thanks! I agree that deep models isn't normally a great idea.

I'm actually already linking to your adaptor under [Step 1: The Adaptor](https://github.com/wmdmark/backbone-rivets-example/blob/master/tutorial.md#step-1-the-adapter) in the tutorial!

**Comment by azproduction** [comment]
Missed that link :) Thanks, Mark!
